// Table tag -> macro-catégorie, dérivée de la taxonomie commune du front
// (eco-tourism-platform-front/lib/constants/taxonomy-tags.ts).
// Elle permet au moteur de recommandation de rapprocher un univers choisi
// par le voyageur (ex. « hebergement ») des tags fins d'une publication
// (ex. « suite », « ecolodge »), sans qu'il ait eu à les cocher un à un.

export const MACRO_SLUGS = [
  'nature',
  'histoire_archeologie',
  'aventure_sport',
  'gastronomie',
  'artisanat',
  'decouverte_urbaine',
  'culture_patrimoine',
  'bien_etre',
  'transport_experientiel',
  'volontariat',
  'hebergement',
] as const;

export const TAG_TO_MACRO: Record<string, string> = {
  // nature
  faune: 'nature',
  flore: 'nature',
  biodiversite: 'nature',
  ornithologie: 'nature',
  geologie: 'nature',
  botanique: 'nature',
  ecologie_marine: 'nature',
  zones_humides: 'nature',
  forets_maquis: 'nature',
  desert_dunes: 'nature',
  oasis: 'nature',
  parcs_naturels: 'nature',
  astronomie: 'nature',
  photographie_nature: 'nature',
  conservation_protection: 'nature',
  observation_faune: 'nature',
  safari_desert: 'nature',
  circuit_nature: 'nature',
  circuit_montagne: 'nature',
  tour_cotier: 'nature',
  // histoire_archeologie
  periode_punique: 'histoire_archeologie',
  periode_romaine: 'histoire_archeologie',
  periode_byzantine: 'histoire_archeologie',
  periode_arabe_medievale: 'histoire_archeologie',
  periode_ottomane: 'histoire_archeologie',
  periode_coloniale: 'histoire_archeologie',
  prehistoire: 'histoire_archeologie',
  fouilles_archeologiques: 'histoire_archeologie',
  mosaiques_antiques: 'histoire_archeologie',
  thermes_romains: 'histoire_archeologie',
  amphitheatres: 'histoire_archeologie',
  necropoles: 'histoire_archeologie',
  ksour_greniers_berberes: 'histoire_archeologie',
  routes_commerciales: 'histoire_archeologie',
  carthage_civilisation_punique: 'histoire_archeologie',
  circuit_historique: 'histoire_archeologie',
  // aventure_sport
  randonnee_pedestre: 'aventure_sport',
  trek_multi_jours: 'aventure_sport',
  escalade: 'aventure_sport',
  via_ferrata: 'aventure_sport',
  speleologie: 'aventure_sport',
  canyoning: 'aventure_sport',
  vtt_cyclisme: 'aventure_sport',
  kayak_canoe: 'aventure_sport',
  surf_windsurf: 'aventure_sport',
  plongee_sous_marine: 'aventure_sport',
  snorkeling: 'aventure_sport',
  quad_4x4: 'aventure_sport',
  bivouac: 'aventure_sport',
  equitation: 'aventure_sport',
  tir_arc: 'aventure_sport',
  peche_traditionnelle: 'aventure_sport',
  // gastronomie
  cuisine_tunisienne_traditionnelle: 'gastronomie',
  cuisine_berbere: 'gastronomie',
  cuisine_cotiere_fruits_mer: 'gastronomie',
  street_food: 'gastronomie',
  epices_condiments: 'gastronomie',
  huile_olive_oleiculture: 'gastronomie',
  dattes_palmeraies: 'gastronomie',
  marches_locaux: 'gastronomie',
  cours_cuisine: 'gastronomie',
  degustation_thes: 'gastronomie',
  vins_viticulture: 'gastronomie',
  boulangerie_traditionnelle: 'gastronomie',
  miel_apiculture: 'gastronomie',
  restaurant_traditionnel: 'gastronomie',
  cafe_salon_the: 'gastronomie',
  ferme_restaurant: 'gastronomie',
  food_truck: 'gastronomie',
  table_hotes: 'gastronomie',
  degustation_produits: 'gastronomie',
  diner_panoramique: 'gastronomie',
  visite_ferme: 'gastronomie',
  cueillette: 'gastronomie',
  atelier_fromage_yaourt: 'gastronomie',
  jardinage: 'gastronomie',
  elevage_responsable: 'gastronomie',
  // artisanat
  poterie_ceramique: 'artisanat',
  tissage_tapis: 'artisanat',
  broderie: 'artisanat',
  bijoux_berberes: 'artisanat',
  bijoux_argent: 'artisanat',
  maroquinerie_cuir: 'artisanat',
  sculpture_bois: 'artisanat',
  thuya_marqueterie: 'artisanat',
  vannerie_alfa: 'artisanat',
  calligraphie: 'artisanat',
  enluminure: 'artisanat',
  teinture_naturelle: 'artisanat',
  dinanderie: 'artisanat',
  savon_artisanal: 'artisanat',
  couture_caftan: 'artisanat',
  tannerie: 'artisanat',
  parfumerie_naturelle: 'artisanat',
  peinture_traditionnelle: 'artisanat',
  // decouverte_urbaine
  architecture_moderne: 'decouverte_urbaine',
  street_art_graffiti: 'decouverte_urbaine',
  quartiers_historiques: 'decouverte_urbaine',
  vie_de_quartier: 'decouverte_urbaine',
  marches_urbains: 'decouverte_urbaine',
  cafes_culture_locale: 'decouverte_urbaine',
  gastronomie_urbaine: 'decouverte_urbaine',
  transport_local: 'decouverte_urbaine',
  scene_artistique: 'decouverte_urbaine',
  musique_nuits_locales: 'decouverte_urbaine',
  shopping_alternatif: 'decouverte_urbaine',
  communautes_locales: 'decouverte_urbaine',
  parcs_espaces_verts: 'decouverte_urbaine',
  port_activites_maritimes: 'decouverte_urbaine',
  // culture_patrimoine
  architecture_islamique: 'culture_patrimoine',
  architecture_romaine: 'culture_patrimoine',
  architecture_coloniale: 'culture_patrimoine',
  musees: 'culture_patrimoine',
  medinas: 'culture_patrimoine',
  traditions_locales: 'culture_patrimoine',
  costumes_bijoux: 'culture_patrimoine',
  musique_traditionnelle: 'culture_patrimoine',
  danse_folklorique: 'culture_patrimoine',
  litterature_poesie: 'culture_patrimoine',
  fetes_festivals: 'culture_patrimoine',
  contes_legendes: 'culture_patrimoine',
  religion_spiritualite: 'culture_patrimoine',
  berbere_amazigh: 'culture_patrimoine',
  art_contemporain: 'culture_patrimoine',
  soiree_culturelle: 'culture_patrimoine',
  spectacle_traditionnel: 'culture_patrimoine',
  atelier_musical: 'culture_patrimoine',
  visite_medina: 'culture_patrimoine',
  visite_musee: 'culture_patrimoine',
  // bien_etre
  hammam_traditionnel: 'bien_etre',
  massage_naturel: 'bien_etre',
  retraite_yoga: 'bien_etre',
  meditation: 'bien_etre',
  bain_thermal: 'bien_etre',
  therapie_plantes: 'bien_etre',
  gommage_savon_noir: 'bien_etre',
  yoga: 'bien_etre',
  // transport_experientiel
  location_velo: 'transport_experientiel',
  caleche: 'transport_experientiel',
  bateau_traditionnel: 'transport_experientiel',
  tuk_tuk: 'transport_experientiel',
  dromadaire: 'transport_experientiel',
  transfert_partage: 'transport_experientiel',
  // volontariat
  plantation_arbres: 'volontariat',
  nettoyage_plage: 'volontariat',
  nettoyage_foret: 'volontariat',
  education_environnementale: 'volontariat',
  jardin_communautaire: 'volontariat',
  sensibilisation_ecoles: 'volontariat',
  // hebergement
  dortoir: 'hebergement',
  chambre_standard: 'hebergement',
  chambre_superieure: 'hebergement',
  suite: 'hebergement',
  bungalow: 'hebergement',
  tente_glamping: 'hebergement',
  gite_rural: 'hebergement',
  maison_hotes: 'hebergement',
  riad_traditionnel: 'hebergement',
  ecolodge: 'hebergement',
  camping_sauvage: 'hebergement',
  ferme_agritouristique: 'hebergement',
};

/** Macros couvertes par une liste de tags fins. */
export function macrosOfTags(tags: string[]): Set<string> {
  const set = new Set<string>();
  for (const tag of tags) {
    const macro = TAG_TO_MACRO[tag];
    if (macro) set.add(macro);
  }
  return set;
}
